name: Makefile CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure 1
      run: git update-index --chmod=+x ./fetch-engine.sh
      
    - name: configure 2
      run: git update-index --chmod=+x ./launch-dedicated.sh
      
    - name: configure 3
      run: git update-index --chmod=+x ./launch-game.sh
      
    - name: configure 4
      run: git update-index --chmod=+x ./utility.sh
    
    - name: configure 5
      run: git update-index --chmod=+x ./packaging/package-all.sh
      
    - name: Install dependencies
      run: make ./packaging/package-all.sh

    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
